// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZf-V2eq2jF_2zhvfjLCPJHkLaaAZcrug',
    appId: '1:386554775899:web:20b0247b10bf2b561df27e',
    messagingSenderId: '386554775899',
    projectId: 'fire-98b6d',
    authDomain: 'fire-98b6d.firebaseapp.com',
    databaseURL: 'https://fire-98b6d-default-rtdb.firebaseio.com',
    storageBucket: 'fire-98b6d.appspot.com',
    measurementId: 'G-MES7Z90SQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD91rc-zSKMtN9sEP_grXjnupTKd0OTzE',
    appId: '1:386554775899:android:3ba1c33b7ec6d9211df27e',
    messagingSenderId: '386554775899',
    projectId: 'fire-98b6d',
    databaseURL: 'https://fire-98b6d-default-rtdb.firebaseio.com',
    storageBucket: 'fire-98b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMS0C4FdLkPp_0yBEwmQsUYjMz_PWOaiY',
    appId: '1:386554775899:ios:5a22233a55bede5e1df27e',
    messagingSenderId: '386554775899',
    projectId: 'fire-98b6d',
    databaseURL: 'https://fire-98b6d-default-rtdb.firebaseio.com',
    storageBucket: 'fire-98b6d.appspot.com',
    iosBundleId: 'com.example.postApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMS0C4FdLkPp_0yBEwmQsUYjMz_PWOaiY',
    appId: '1:386554775899:ios:5a22233a55bede5e1df27e',
    messagingSenderId: '386554775899',
    projectId: 'fire-98b6d',
    databaseURL: 'https://fire-98b6d-default-rtdb.firebaseio.com',
    storageBucket: 'fire-98b6d.appspot.com',
    iosBundleId: 'com.example.postApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZf-V2eq2jF_2zhvfjLCPJHkLaaAZcrug',
    appId: '1:386554775899:web:be6600c53eafe6c11df27e',
    messagingSenderId: '386554775899',
    projectId: 'fire-98b6d',
    authDomain: 'fire-98b6d.firebaseapp.com',
    databaseURL: 'https://fire-98b6d-default-rtdb.firebaseio.com',
    storageBucket: 'fire-98b6d.appspot.com',
    measurementId: 'G-85B9RRN47V',
  );
}
